on: [push]

jobs:
  my-job:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Himaja Kanampalli'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory1 }}
        echo "total memory successfully output"
